spring:
  application:
    name: idm-app

server:
  port: ${PORT:8080}

app:
  environment: ${APP_ENV:local}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
